agents:
  - agent_ls
  - agent_dc
  - agent_bat
location: ca
city_name: ''
ci_location: ''
cintensity_file: 'NYIS_NG_&_avgCI.csv'
weather_file: ''
epw_manifest_file: 'data/epw_download_toolkit/validated_manifest.csv'
epw_dir: 'data/epw_download_toolkit/epw_files'
ocean_file: 'data/sst_download_toolkit/sea_surface_temperature_2025_openmeteo.csv'
ocean_city: ''
ocean_temp_column: 'seawater_temp_c'
ocean_time_column: 'timestamp'
workload_file: 'Alibaba_CPU_Data_Hourly_1.csv'
max_bat_cap_Mw: 1.0
individual_reward_weight: 0.8
flexible_load: 0.6
ls_reward: default_ls_reward
dc_reward: default_dc_reward
bat_reward: default_bat_reward
dc_config_file: 'dc_config.json'
cooling_system_mode:
month: 6
days_per_episode: 30
partial_obs: True
nonoverlapping_shared_obs_space: True
